const chatHistoryData = [
    "Windows 11优化工具推荐",
    "Photoshop 2024正版下载咨询",
    "最佳杀毒软件性能对比",
    "Steam游戏平台安装问题",
    "Office 2024专业版下载指南",
    "Adobe全家桶安装包询问",
    "AutoCAD学生版获取方法",
    "虚拟机软件性能测试结果",
    "视频剪辑软件推荐（低配置PC）",
    "正版Windows密钥购买建议",
    "Chrome浏览器插件安全咨询",
    "固态硬盘检测工具下载",
    "Python开发环境配置指导",
    "游戏加速器哪个最有效？",
    "MacBook双系统安装教程",
    "3D建模软件学习版咨询",
    "数据恢复软件真实评测",
    "企业级VPN软件推荐",
    "PC温度监控工具对比",
    "MacBook双系统安装教程",
    "3D建模软件学习版咨询",
    "数据恢复软件真实评测",
    "企业级VPN软件推荐",
    "PC温度监控工具对比",
    "旧电脑重装系统最佳方案",
    
];

export default chatHistoryData;